package com.kuwait.showroomz.extras

import com.kuwait.showroomz.BuildConfig
import com.kuwait.showroomz.extras.managers.DeviceManger


const val BASE_URL = BuildConfig.BASE_URL
const val API_URL = "$BASE_URL${BuildConfig.API_VERSION}"

const val CATEGORIES_API = "categories"
const val CATEGORIES_BY_ID_API = "categories%d"

const val BRAND_LOCATION_API = "brand-locations"
const val DEALER_LOCATION_API = "dealer-locations"
const val BRAND_MODELS="-data-model-datas"
const val INCREMENT_MODEL_VIEW="model-datas/{id}/nb-views/increment"
const val MODEL_TYPE="model-types"
const val BRAND_MODELS_DATA="brand-data-model-datas"
const val GET_MODEL_GALLERY="model-data/{id}/image-gallery"
const val GET_MODEL_VIDEOS="model-data/{id}/video-gallery"
const val MODEL_DATA="-data-model-data"
const val TRIMS_OFFERS="trims-and-offers"
const val GET_ALL_BANKS="banks"
const val GET_ADS="advertisements?_page=0&itemsPerPage=400"
const val RECENTLY_VIEWED="RECENTLY_VIEWED"
const val DISPLAYED_ADS="DISPLAYED_ADS"
const val INCREMENT_ADS_VIEW="advertisements/{id}/nb-views/increment"
const val INCREMENT_ADS_CLICK="advertisements/{id}/nb-clicks/increment"
const val LAST_SHOW_TIME_ADS="LAST_SHOW_TIME_ADS"
const val SETTINGS="settings"
const val LOGIN="Clients/login"
const val LOGINSOCIAL="Clients/login-social"
const val REGISTER="Clients/register"
const val REGISTERSOCIAL="Clients/register-social"
const val ME="authenticated/clients/get/me"
const val TOKEN="TOKEN"
const val USER_ID="USER_ID"
const val FIRST_INSTALLATION="FIRST_INSTALLATION"
const val LAST_SESSION="LAST_SESSION"
const val RESET_PASSWORD="Clients/forgot-password"
const val CHANGE_PASSWORD="Clients/edit/password"
const val RESET_PASSWORD_OTP ="Clients/reset/password"
const val UPDATE_PROFILE="Clients/{id}"
const val LOGOUT="authenticated/clients/logout?serialNumber="
const val CALLBACK_APPRAISAL="callback-appraisal-client-vehicle-requests/{id}"
const val GET_CALLBACKS="callbacks"
const val GET_CALLBACKSADS="callback-advertisements"
const val CALLBACK_LOCATION="callback-maintenances"
const val GET_CALLBACKS_BY_ID="callbacks/{id}"
const val CALLBACK_BANKS="callback-banks"
const val TEST_DRIVE_AT_SHOWROOM="test-drive/test-drive-at-showrooms"
const val TEST_DRIVE_WITH_DELIVERY="test-drive/test-drive-atwith-deliveries"
const val CLIENT_ADDRESS="client-addresses"
const val FAVORITE_MODELS="favorite-client-model-datas"
const val GET_PREFERRED_TIME="test-drive/get-preferred-times"
const val PREFERRED_TIME ="PREFERRED_TIME"
const val MODEL_ID ="MODEL_ID"
const val TEST_DRIVE="test-drive"
const val IMAGES="Media"
const val MEDIA="Media"
const val MEDIA_GET="media-get"
const val CALLBACK_BANK="CallbackBank"
const val IMAGE_URL="$API_URL$MEDIA"
const val CLIENT_PAYMENT_BOOKING="client-payment"
const val CLIENT_PAYMENT_RENT="client-payment"
const val CLIENT_PAYMENT_BUYING="client-payment"
const val GET_PAYMENTS="client-payment"
const val PAYMENT_GATEWAY = BuildConfig.PAYMENT_URL
const val PAYMENT_SUCCESS ="//payment/success"
const val PAYMENT_RESULT ="PAYMENT_RESULT"
const val PAYMENT_FAIL ="/payment/fail"
const val DEVICE_ID ="device_id"
const val ABOUT_APP_URL ="aboutus"
const val TERM_CONDITION_URL ="termsandconditions"
const val CONTACT_NUMBER="+96599516512"
const val CONTACT_EMAIL="info@showroomz.com"
const val CLIENT_VEHICLES="client-vehicles"
const val INDUSTRIES="industries"
const val APPRAISAL_CAR_OPTIONS="appraisal-vehicle-options"
const val REGISTER_DEVICE="devices/"
const val INCREMENT_NBR_DOWNLOADS="devices/create-or-increment-nbr-downloads"
const val DEVICE_ACTIVITY_LOG_START="device-activity-log-start"
const val DEVICE_ACTIVITY_LOG_STOP="device-activity-log-stop"
const val DEVICE_ACTIVITY_LOG_PROGRESS="device-activity-log-progress"
const val SEARCH_LOG="/search-logs"
const val CALLBACK_APPRAISAL_CLIENT_VEHICLES="callback-appraisal-client-vehicle-requests"



const val BRANDSTOCKAPI = "brands?_page=0&itemsPerPage=700"
const val AGENCIESSTOCKAPI = "agencies?_page=0&itemsPerPage=700"
const val BRANDSLIGHT = "dealer-datas-light-get?_page=0&itemsPerPage=500"
const val AllModelsApiLight = "model-datas-light-get?_page=%d&itemsPerPage=200"
const val MODELSSTOCK = "models?_page=%d&itemsPerPage=200"
const val ACTIONS = "model-data-actions"
const val ACTIONSADS = "callback-ads-actions"

const val PHONECODEREQUEST= "clients/phone-code-request"
const val PHONECODEVERIFY = "clients/phone-code-validation"
const val APPRAISALINFOAPI= "appraisal-vehicle-brands?_page=0&itemsPerPage=200"

const val MODEL_DATAS_WITH_SLUG="model-datas-light-get?slug="
const val MODEL_DATAS_WITH_ID="model-datas/"
const val BRAND_DATAS_WITH_SLUG="dealer-datas?slug="
const val CATEGORIES_WITH_SLUG="categories?slug="
const val TRIM_OFFERS="offer-trims"
const val PANORAMA_URL = "https://admin.showroomz.com/panorama/index.html?view="




